### ISSUE TITLE
No module named 'pooch'

### ISSUE THREAD

**Issue by stonemoonkey** [zzheng93/pyEOF#1]
basic_usage.ipynb
when I run this block
# load the DataArray 
da = xr.tutorial.open_dataset('air_temperature')["air"]
print(da)

# create a mask
mask = da.sel(time=da.time[0])
mask = mask.where(mask<250).isnull().drop("time")

# get the DataArray with mask
da = da.where(mask)
da.sel(time=da.time[99]).plot()
plt.show()

there is complain of No module named 'pooch'
 after installing Scikit-image, the problem was solved

**Comment by zhonghua-zheng** [comment]
@stonemoonkey Thank you! I have added a note to the tutorial. https://pyeof.readthedocs.io/en/latest/notebooks/basic_usage.html
