### ISSUE TITLE
df_eof is not defined

### ISSUE THREAD

**Issue by qq492947833** [zzheng93/pyEOF#2]
when i use your code,the jupyter notebook raise a error,'df_eof is not defined',your documention is not explain that what mean is 'df_eof',can you solve my problem?Thank you

**Comment by zhonghua-zheng** [comment]
Hello @qq492947833 , have you tried the online tutorial? https://mybinder.org/v2/gh/zzheng93/pyEOF/HEAD?filepath=docs%2Fnotebooks
```
from pyEOF import *
print(df_eof)
```
It would show "df_eof" is "<class 'pyEOF.pyEOF.df_eof'>"

**Comment by qq492947833** [comment]
sorry,I solve this problem。But there have new problem，python 3 cant change the defalut encoding，it always is 'utf-8'，but the rpy2 not support that。it will be raise a error ‘'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte’。so how can I solve this problem？Thanks a lot！

**Comment by qq492947833** [comment]
![QQ截图20210628202851](https://user-images.githubusercontent.com/81745297/123636668-b7a51f00-d84f-11eb-890b-2a2b815e41ce.png)
And when I use my netcdf4 file with your code,it will raise a error like that.

**Comment by qq492947833** [comment]
I think the df is as same as original df in your code.

**Comment by zhonghua-zheng** [comment]
> ![QQ截图20210628202851](https://user-images.githubusercontent.com/81745297/123636668-b7a51f00-d84f-11eb-890b-2a2b815e41ce.png)
> And when I use my netcdf4 file with your code,it will raise a error like that.

Hi @qq492947833 , I just tried the [online tutorial](https://mybinder.org/v2/gh/zzheng93/pyEOF/HEAD?filepath=docs%2Fnotebooks) again and couldn't reproduce the errors. It is difficult to solve your problem without knowing your setup and code.

So I think there are two possible reasons that you got the errors:
- installation
- data

First, please follow the instruction strictly to install the pyEOF package (**including [creating a new conda environment](https://pyeof.readthedocs.io/en/latest/installation.html)**)

If you still get the errors, please share **a sample of your data** and your jupyter notebook that **reproduces the error with the sample data**, then I can help to debug.

Thanks!

**Comment by qq492947833** [comment]
Sorry, I checked my environment and data and didn't find any problems with them！
I'm sorry for my problem. I'd appreciate it if you could help me.Since I use my own functions, I will briefly explain the purpose of these functions.
The data I use is the precipitation of CPC, which is daily data（figure 1 and file1）.
![QQ截图20210629120621](https://user-images.githubusercontent.com/81745297/123735955-c7197c00-d8d2-11eb-92ca-b5493b07d71d.png)

 I use my own function to open it. If you need to use this function, you just need to modify the file read path（figure 2，）
![QQ截图20210629120942](https://user-images.githubusercontent.com/81745297/123736048-f7611a80-d8d2-11eb-8db3-2e7e373070f5.png)
In Figure 2, you just need to modify 'H / Precip. NC' to your own path. Function 'open'_ data_ NC 'has been tested repeatedly, and its function and correctness can be guaranteed.

Then I did another filtering operation, in order to extract the signal for 10-80 days. I use 'AutoBar' here_ or_ The line 'function (Figure 3) is still written by me, but it has been tested many times. You don't need to change this function (or you can delete it directly from the code if you think it's unnecessary). As you can see, although filtered, I finally restored the filtered results to the format of XR. Dataarray（Figure 4）.
![QQ截图20210629121228](https://user-images.githubusercontent.com/81745297/123736416-a56cc480-d8d3-11eb-9afe-378ce4da67c0.png)
![QQ截图20210629121531](https://user-images.githubusercontent.com/81745297/123736459-b9b0c180-d8d3-11eb-8768-da67b5e9a72f.png)

Then you use your code, followed by the previous error. I will also send you my code in. Ipynb format.
[REOF.zip](https://github.com/zzheng93/pyEOF/files/6730640/REOF.zip)

In fact, I'm a graduate student from NUIST，and I'm also writing some functions and code myself（website：http://bbs.06climate.com/forum.php?mod=viewthread&tid=97940&extra=&page=1）. I use simple functions (not class, but def) to do data processing and drawing. Before using the EOFs library to EOF, but there is no REOF code on the network, so I found your function library. I sincerely hope to introduce your functions into my automatic drawing system, and also hope that your functions and my functions can help more beginners.

If you can introduce your function into my function system, I will be very honored!

Thank you again for your great contribution to the scientific research field!

**Comment by qq492947833** [comment]
I have sent my code and data to you by email, my email address is 492947833@qq.com，
![QQ截图20210629160829](https://user-images.githubusercontent.com/81745297/123761297-44a1b400-d8f4-11eb-9740-55f49e2ee813.png)
thank you！

**Comment by zhonghua-zheng** [comment]
Hi @qq492947833  , I was able to reproduce the error with the files that you sent me in the email.

The error comes from your "df". With the command
```python
list(df)
```
you would get `[('time',), ('lat',), ('lon',), ('preicp',)]`
So the solution is
```python
df.columns = ["time","lat","lon","preicp"]
list(df) 
```
It would return `['time', 'lat', 'lon', 'preicp']` and solve the issue.

Besides, I noticed that your data has some missing values (in addition to the "missing values" induced by "mask"). So you should process your data before performing the EOFs analysis.

```python
# the shape of the matrix after removing the missing values from mask
print(x.shape)
# missing values in the matrix
np.argwhere(np.isnan(x))
```
```
(14337, 9385)

array([[  694,     0],
       [  694,     1],
       [  694,     2],
       ...,
       [10968,  9358],
       [10968,  9359],
       [10968,  9360]])
```
Some locations have missing values on some days (not always missing). Please check my email for more information on that.
