### ISSUE TITLE
Error reporting problem

### ISSUE THREAD

**Issue by lizheng1111** [zzheng93/pyEOF#4]
Do it in order, and the following error is reported: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte.
What should I do？

**Comment by zhonghua-zheng** [comment]
Hi, please see here: https://github.com/zzheng93/pyEOF/issues/2

**Comment by lizheng1111** [comment]
Sorry, I don't quite understand why `list(df)`, I fill in the missing value and then appear ''utf-8'' error.

**Comment by zhonghua-zheng** [comment]
The command `list(df)` shows your column names, which should be a list of strings. 
You may post a screenshot of your code and error messages here. Without your code, it is challenging to comprehend your issue.

**Comment by lizheng1111** [comment]
![Snipaste_2022-07-05_12-41-48](https://user-images.githubusercontent.com/108670358/177251093-461bdee6-7807-47a4-99fe-02829f552e6e.png)
![2](https://user-images.githubusercontent.com/108670358/177251208-136c9bee-402a-421e-8622-e96ecd4801a0.png)

![3](https://user-images.githubusercontent.com/108670358/177251125-8fd8e9db-8b38-4f35-9d3a-24ad849790dc.png)
358/177251114-7734d6c5-012e-40d5-8682-3e24e4898662.png)

**Comment by zhonghua-zheng** [comment]
Could you please type `list(df)` between [22] and [23]?

**Comment by lizheng1111** [comment]
![4](https://user-images.githubusercontent.com/108670358/177252649-1d7391a5-dd3d-4640-8775-72947f1d2917.png)
![5](https://user-images.githubusercontent.com/108670358/177252659-beb245e5-1fe2-4432-9532-51adabcfcb4e.png)
There are still problems

**Comment by zhonghua-zheng** [comment]
Can you share a sample of your data and your code via Google Drive, so that I can download and reproduce the error?

**Comment by lizheng1111** [comment]
Sorry, I haven't used that. Can I send it to your email？

**Comment by zhonghua-zheng** [comment]
Any form of cloud storage should be fine. The storage limit prevents me from receiving an email for the data (code is OK).

**Comment by lizheng1111** [comment]
https://drive.google.com/drive/folders/1gxQEkyY74bwXjJZl5gBN_-PunaZ_VpCO?usp=sharing

**Comment by lizheng1111** [comment]
Hello, Professor Zheng, has my code been uploaded successfully

**Comment by zhonghua-zheng** [comment]
Hi, I can download what you have uploaded. I will check it later this week. @lizheng1111

**Comment by zhonghua-zheng** [comment]
Hi @lizheng1111 , after reviewing your code and data, I believe that the locations of missing values in your f1 files are shifting over time.
Comparing the first and second timestamps reveals that the mask is distinct.

Please note:
- We cannot use a "time-variant mask".
- Also, please don't replace "np.nan" with "0".

![image](https://user-images.githubusercontent.com/23510121/177917544-edd31408-f207-4e8a-9e8d-020d099dedd2.png)

**Comment by lizheng1111** [comment]
What do I need to do to deal with missing tests to use REOF

**Comment by zhonghua-zheng** [comment]
I am considering two approaches:
1. missing data imputation 
2. if you find a location at a timestamp with a missing value, you should mask it along the time axis

**Comment by lizheng1111** [comment]
I agree with you and think that the second method is feasible, and the first method may cause false values
