### ISSUE TITLE
R[write to console]: Error in La.svd(B) : infinite or missing values  in 'x'

### ISSUE THREAD

**Issue by imronade** [zzheng93/pyEOF#5]
I tried to run the code as in the tutorial you provided. For the value of nan I tried to replace it with the average value then I tried to run 'pca = df_eof(df_data,pca_type="varimax",n_components=n)' but I get error 'R[write to console]: Error in La.svd (B) : infinite or missing values ​​in 'x''

I tried to search on google but still nothing

am I wrong if I skip the mask step in your tutorial?

**Comment by zhonghua-zheng** [comment]
Hi @imronade , you may check if you have all zeros in some rows.

**Comment by imronade** [comment]
I tried to check the value by calculating the unique value and i got:

```
>>> df['layer'].value_counts() 
0.413406    1116384
1.000000       8301
0.000000         47
0.333333          9
0.200000          8
             ...
0.239492          1
0.086097          1
0.221268          1
0.113022          1
0.061587          1
Name: layer, Length: 36325, dtype: int64
```

**Comment by imronade** [comment]
> Hi @imronade , you may check if you have all zeros in some rows.

any suggestions?

**Comment by zhonghua-zheng** [comment]
@imronade Did you replace the "nan" successfully? For a matrix, the algorithm will check if the entire column(s) are "nan", and then treat them separately.

**Comment by imronade** [comment]
the data that i used like this: 
```
>>> da = xr.open_mfdataset('data/NETCDF0p5_SCALED/*.nc',
...                         combine='nested', concat_dim="time")['layer']
>>> 
>>> print(da)
<xarray.DataArray 'layer' (time: 240, latitude: 44, longitude: 110)> 
dask.array<concatenate, shape=(240, 44, 110), dtype=float32, chunksize=(1, 44, 110), chunktype=numpy.ndarray>
Coordinates:
  * longitude  (longitude) float64 90.25 90.75 91.25 91.75 ... 143.8 
144.2 144.8
  * latitude   (latitude) float64 9.75 9.25 8.75 8.25 ... -10.75 -11.25 -11.75
Dimensions without coordinates: time
Attributes:
    grid_mapping:  crs
    proj4:         +proj=longlat +datum=WGS84 +no_defs
    min:           0.0
    max:           1.0
```
then i add times dimension to the data 

```
# add time dimension to data
times = pd.date_range("2001/01/01","2020/12/31",freq='M')
# time_da = xr.DataArray(times, [('time', times)])
da.coords['time'] = ('time',times)
```

next, i skip the mask then go to:

```
# convert DataArray to DataFrame
df = ds.to_dataframe().reset_index() # get df from da
df.head(5)
print("DataFrame Shape:",df.shape)

# preprocessing with NaN values with mean value
df['layer'] = df['layer'].fillna((df['layer'].mean()))
```

**Comment by zhonghua-zheng** [comment]
Can you share the data so that I can reproduce the error? Certainly mask is not necessary for REOF.

**Comment by imronade** [comment]
> Can you share the data so that I can reproduce the error? Certainly mask is not necessary for REOF.

you can donwload here: https://drive.google.com/drive/folders/1O442FM2ULvrF9VkelY0ldb0_rkm9kq-7?usp=sharing

**Comment by zhonghua-zheng** [comment]
![image](https://user-images.githubusercontent.com/23510121/179449198-f039bd0c-df6f-4b04-806e-018778a762d3.png)
I just tried "200101.nc" and "200102.nc". You can find the masks are different.

**Comment by zhonghua-zheng** [comment]
@imronade Please note that we cannot use a "time-variant mask."
See https://github.com/zzheng93/pyEOF/issues/4 for more information.
